export * as notfound from './404.md'
export * as advertise from './advertise.md'
export * as careers from './careers.md'
export * as contact from './contact.md'
export * as legal from './legal.md'
export * as press from './press.md'
export * as training from './training.md'
